[[redirects]]
  from = "/api/*"
  to = "https://leetcode.com:splat"
  status = 200

[[redirects]]
  from = "/graphql/*"
  to = "https://leetcode.com:splat"
  status = 200

[[redirects]]
  from = "/repo*"
  to = "https://api.github.com"
  status = 200

[[redirects]]
  from = "/user*"
  to = "https://api.github.com"
  status = 200
