[[redirects]]
  from = "/api/*"
  to = "https://leetcode.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/graphql/*"
  to = "https://leetcode.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/repos"
  to = "https://api.github.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/repos/"
  to = "https://api.github.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/user/*"
  to = "https://api.github.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

  [[redirects]]
  from = "/user"
  to = "https://api.github.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}
