[[redirects]]
  from = "/api/problems/algorithms"
  to = "https://leetcode.com/api/problems/algorithms"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/graphql/*"
  to = "https://leetcode.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/list/*"
  to = "https://leetcode.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/repo*"
  to = "https://api.github.com"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/user/repos"
  to = "https://api.github.com/user/repos"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/user"
  to = "https://api.github.com/user"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}
