export const languages = {
  python: '.py',
  python3: '.py',
  'C++': '.cpp',
  cpp: '.cpp',
  c: '.c',
  java: '.java',
  'C#': '.cs',
  cs: '.cs',
  javaScript: '.js',
  javascript: '.js',
  ruby: '.rb',
  swift: '.swift',
  go: '.go',
  kotlin: '.kt',
  scala: '.scala',
  rust: '.rs',
  php: '.php',
  typeScript: '.ts',
  mySQL: '.sql',
  'MS SQL Server': '.sql',
  oracle: '.sql',
};
